/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../../index";

/**
 * @example
 *     {
 *         queries: [{
 *                 table: "call",
 *                 name: "name",
 *                 operations: [{
 *                         operation: "sum",
 *                         column: "id"
 *                     }]
 *             }]
 *     }
 */
export interface AnalyticsQueryDto {
    /** This is the list of metric queries you want to perform. */
    queries: Vapi.AnalyticsQuery[];
}
