/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class VapiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, VapiTimeoutError.prototype);
    }
}
