/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UpdateCallDto {
    /** This is the name of the call. This is just for your own reference. */
    name?: string;
}
