/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddVoiceToProviderDto {
    /** This is the owner_id of your shared voice which you want to add to your provider Account from Provider Voice Library */
    ownerId: string;
    /** This is the voice_id of the shared voice which you want to add to your provider Account from Provider Voice Library */
    voiceId: string;
    /** This is the new name of the voice which you want to have once you have added voice to your provider Account from Provider Voice Library */
    name: string;
}
