/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AnalyticsQueryGroupByItem =
    | "type"
    | "assistantId"
    | "endedReason"
    | "analysis.successEvaluation"
    | "status";

export const AnalyticsQueryGroupByItem = {
    Type: "type",
    AssistantId: "assistantId",
    EndedReason: "endedReason",
    AnalysisSuccessEvaluation: "analysis.successEvaluation",
    Status: "status",
} as const;
