/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the columns you want to perform the aggregation operation on.
 */
export type AnalyticsOperationColumn =
    | "id"
    | "cost"
    | "costBreakdown.llm"
    | "costBreakdown.stt"
    | "costBreakdown.tts"
    | "costBreakdown.vapi"
    | "costBreakdown.ttsCharacters"
    | "costBreakdown.llmPromptTokens"
    | "costBreakdown.llmCompletionTokens"
    | "duration";

export const AnalyticsOperationColumn = {
    Id: "id",
    Cost: "cost",
    CostBreakdownLlm: "costBreakdown.llm",
    CostBreakdownStt: "costBreakdown.stt",
    CostBreakdownTts: "costBreakdown.tts",
    CostBreakdownVapi: "costBreakdown.vapi",
    CostBreakdownTtsCharacters: "costBreakdown.ttsCharacters",
    CostBreakdownLlmPromptTokens: "costBreakdown.llmPromptTokens",
    CostBreakdownLlmCompletionTokens: "costBreakdown.llmCompletionTokens",
    Duration: "duration",
} as const;
