/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the type of analysis performed.
 */
export type AnalysisCostAnalysisType = "summary" | "structuredData" | "successEvaluation";

export const AnalysisCostAnalysisType = {
    Summary: "summary",
    StructuredData: "structuredData",
    SuccessEvaluation: "successEvaluation",
} as const;
