/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the Anthropic/Claude models that will be used.
 */
export type AnthropicModelModel =
    | "claude-3-opus-20240229"
    | "claude-3-sonnet-20240229"
    | "claude-3-haiku-20240307"
    | "claude-3-5-sonnet-20240620";

export const AnthropicModelModel = {
    Claude3Opus20240229: "claude-3-opus-20240229",
    Claude3Sonnet20240229: "claude-3-sonnet-20240229",
    Claude3Haiku20240307: "claude-3-haiku-20240307",
    Claude35Sonnet20240620: "claude-3-5-sonnet-20240620",
} as const;
