/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type AnthropicModelToolsItem =
    | Vapi.CreateDtmfToolDto
    | Vapi.CreateEndCallToolDto
    | Vapi.CreateVoicemailToolDto
    | Vapi.CreateFunctionToolDto
    | Vapi.CreateGhlToolDto
    | Vapi.CreateMakeToolDto
    | Vapi.CreateTransferCallToolDto;
