/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the background sound in the call. Default for phone calls is 'office' and default for web calls is 'off'.
 */
export type AssistantBackgroundSound = "off" | "office";

export const AssistantBackgroundSound = {
    Off: "off",
    Office: "office",
} as const;
