/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssistantClientMessagesItem =
    | "conversation-update"
    | "function-call"
    | "function-call-result"
    | "hang"
    | "language-changed"
    | "metadata"
    | "model-output"
    | "speech-update"
    | "status-update"
    | "transcript"
    | "tool-calls"
    | "tool-calls-result"
    | "user-interrupted"
    | "voice-input";

export const AssistantClientMessagesItem = {
    ConversationUpdate: "conversation-update",
    FunctionCall: "function-call",
    FunctionCallResult: "function-call-result",
    Hang: "hang",
    LanguageChanged: "language-changed",
    Metadata: "metadata",
    ModelOutput: "model-output",
    SpeechUpdate: "speech-update",
    StatusUpdate: "status-update",
    Transcript: "transcript",
    ToolCalls: "tool-calls",
    ToolCallsResult: "tool-calls-result",
    UserInterrupted: "user-interrupted",
    VoiceInput: "voice-input",
} as const;
