/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * These are the options for the assistant's LLM.
 */
export type AssistantModel =
    | Vapi.AnyscaleModel
    | Vapi.AnthropicModel
    | Vapi.CustomLlmModel
    | Vapi.DeepInfraModel
    | Vapi.GroqModel
    | Vapi.OpenAiModel
    | Vapi.OpenRouterModel
    | Vapi.PerplexityAiModel
    | Vapi.TogetherAiModel
    | Vapi.VapiModel;
