/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AzureOpenAiCredentialModelsItem =
    | "gpt-4o-mini-2024-07-18"
    | "gpt-4o-2024-05-13"
    | "gpt-4-turbo-2024-04-09"
    | "gpt-4-0125-preview"
    | "gpt-4-1106-preview"
    | "gpt-4-0613"
    | "gpt-35-turbo-0125"
    | "gpt-35-turbo-1106";

export const AzureOpenAiCredentialModelsItem = {
    Gpt4OMini20240718: "gpt-4o-mini-2024-07-18",
    Gpt4O20240513: "gpt-4o-2024-05-13",
    Gpt4Turbo20240409: "gpt-4-turbo-2024-04-09",
    Gpt40125Preview: "gpt-4-0125-preview",
    Gpt41106Preview: "gpt-4-1106-preview",
    Gpt40613: "gpt-4-0613",
    Gpt35Turbo0125: "gpt-35-turbo-0125",
    Gpt35Turbo1106: "gpt-35-turbo-1106",
} as const;
