/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AzureVoiceIdEnum = "andrew" | "brian" | "emma";

export const AzureVoiceIdEnum = {
    Andrew: "andrew",
    Brian: "brian",
    Emma: "emma",
} as const;
