/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the provider of the call.
 *
 * Only relevant for `outboundPhoneCall` and `inboundPhoneCall` type.
 */
export type CallPhoneCallProvider = "twilio" | "vonage" | "vapi";

export const CallPhoneCallProvider = {
    Twilio: "twilio",
    Vonage: "vonage",
    Vapi: "vapi",
} as const;
