/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the block to use. To use an existing block, use `blockId`.
 */
export type CallbackStepBlock =
    | Vapi.CreateConversationBlockDto
    | Vapi.CreateToolCallBlockDto
    /**
     * This is the CreateWorkflowBlockDTO object but Swagger does not display nested schemas correctly. */
    | Vapi.CreateWorkflowBlockDto;
