/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the destination where the call ended up being transferred to. If the call was not transferred, this will be empty.
 */
export type CallDestination = Vapi.TransferDestinationNumber | Vapi.TransferDestinationSip;
