/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the transport of the phone call.
 *
 * Only relevant for `outboundPhoneCall` and `inboundPhoneCall` type.
 */
export type CallPhoneCallTransport = "sip" | "pstn";

export const CallPhoneCallTransport = {
    Sip: "sip",
    Pstn: "pstn",
} as const;
