/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CartesiaVoice {
    /**
     * This determines whether fillers are injected into the model output before inputting it into the voice provider.
     *
     * Default `false` because you can achieve better results with prompting the model.
     */
    fillerInjectionEnabled?: boolean;
    /** This is the voice provider that will be used. */
    provider: "cartesia";
    /** This is the model that will be used. This is optional and will default to the correct model for the voiceId. */
    model?: Vapi.CartesiaVoiceModel;
    /** This is the language that will be used. This is optional and will default to the correct language for the voiceId. */
    language?: Vapi.CartesiaVoiceLanguage;
    /** This is the provider-specific ID that will be used. */
    voiceId: string;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: Vapi.ChunkPlan;
}
