/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the language that will be used. This is optional and will default to the correct language for the voiceId.
 */
export type CartesiaVoiceLanguage = "de" | "en" | "es" | "fr" | "ja" | "pt" | "zh";

export const CartesiaVoiceLanguage = {
    De: "de",
    En: "en",
    Es: "es",
    Fr: "fr",
    Ja: "ja",
    Pt: "pt",
    Zh: "zh",
} as const;
