/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used. This is optional and will default to the correct model for the voiceId.
 */
export type CartesiaVoiceModel = "sonic-english" | "sonic-multilingual";

export const CartesiaVoiceModel = {
    SonicEnglish: "sonic-english",
    SonicMultilingual: "sonic-multilingual",
} as const;
