/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientInboundMessage {
    /** These are the messages that can be sent from client-side SDKs to control the call. */
    message: Vapi.ClientInboundMessageMessage;
}
