/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * These are all the messages that can be sent to the client-side SDKs during the call. Configure the messages you'd like to receive in `assistant.clientMessages`.
 */
export type ClientMessageMessage =
    | Vapi.ClientMessageConversationUpdate
    | Vapi.ClientMessageHang
    | Vapi.ClientMessageMetadata
    | Vapi.ClientMessageModelOutput
    | Vapi.ClientMessageSpeechUpdate
    | Vapi.ClientMessageTranscript
    | Vapi.ClientMessageToolCalls
    | Vapi.ClientMessageToolCallsResult
    | Vapi.ClientMessageUserInterrupted
    | Vapi.ClientMessageLanguageChanged
    | Vapi.ClientMessageVoiceInput;
