/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the role for which the transcript is for.
 */
export type ClientMessageTranscriptRole = "assistant" | "user";

export const ClientMessageTranscriptRole = {
    Assistant: "assistant",
    User: "user",
} as const;
