/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientInboundMessageControl {
    /**
     * This is the type of the message. Send "control" message to control the assistant. `control` options are:
     *
     * - "mute-assistant" - mute the assistant
     * - "unmute-assistant" - unmute the assistant
     * - "say-first-message" - say the first message (this is used when video recording is enabled and the conversation is only started once the client side kicks off the recording)
     */
    type: "control";
    /** This is the control action */
    control: Vapi.ClientInboundMessageControlControl;
}
