/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientMessageMetadata {
    /** This is the type of the message. "metadata" is sent to forward metadata to the client. */
    type: "metadata";
    /** This is the metadata content */
    metadata: string;
}
