/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientMessageVoiceInput {
    /** This is the type of the message. "voice-input" is sent when a generation is requested from voice provider. */
    type: "voice-input";
    /** This is the voice input content */
    input: string;
}
