/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the type of the transcript.
 */
export type ClientMessageTranscriptTranscriptType = "partial" | "final";

export const ClientMessageTranscriptTranscriptType = {
    Partial: "partial",
    Final: "final",
} as const;
