/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClientMessageUserInterrupted {
    /** This is the type of the message. "user-interrupted" is sent when the user interrupts the assistant. */
    type: "user-interrupted";
}
