/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientMessageConversationUpdate {
    /** This is the type of the message. "conversation-update" is sent when an update is committed to the conversation history. */
    type: "conversation-update";
    /** This is the most up-to-date conversation history at the time the message is sent. */
    messages?: Vapi.ClientMessageConversationUpdateMessagesItem[];
    /** This is the most up-to-date conversation history at the time the message is sent, formatted for OpenAI. */
    messagesOpenAIFormatted: Vapi.OpenAiMessage[];
}
