/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ClientMessageToolCalls {
    /** This is the type of the message. "tool-calls" is sent to call a tool. */
    type?: "tool-calls";
    /** This is the list of tools calls that the model is requesting along with the original tool configuration. */
    toolWithToolCallList: Vapi.ClientMessageToolCallsToolWithToolCallListItem[];
    /** This is the list of tool calls that the model is requesting. */
    toolCallList: Vapi.ToolCall[];
}
