/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CloneVoiceDto {
    /** This is the name of the cloned voice in the provider account. */
    name: string;
    /** This is the description of your cloned voice. */
    description?: string;
    /** Serialized labels dictionary for the voice. */
    labels?: string;
    /** These are the files you want to use to clone your voice. Only Audio files are supported. */
    files: string[];
}
