/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the operator you want to use to compare the parameter and value.
 */
export type ConditionOperator = "eq" | "neq" | "gt" | "gte" | "lt" | "lte";

export const ConditionOperator = {
    Eq: "eq",
    Neq: "neq",
    Gt: "gt",
    Gte: "gte",
    Lt: "lt",
    Lte: "lte",
} as const;
