/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CostBreakdown {
    /** This is the cost of the transport provider, like Twilio or Vonage. */
    transport?: number;
    /** This is the cost of the speech-to-text service. */
    stt?: number;
    /** This is the cost of the language model. */
    llm?: number;
    /** This is the cost of the text-to-speech service. */
    tts?: number;
    /** This is the cost of Vapi. */
    vapi?: number;
    /** This is the total cost of the call. */
    total?: number;
    /** This is the LLM prompt tokens used for the call. */
    llmPromptTokens?: number;
    /** This is the LLM completion tokens used for the call. */
    llmCompletionTokens?: number;
    /** This is the TTS characters used for the call. */
    ttsCharacters?: number;
    /** This is the cost of the analysis. */
    analysisCostBreakdown?: Vapi.AnalysisCostBreakdown;
}
