/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateGladiaCredentialDto {
    provider: "gladia";
    /** This is not returned in the API. */
    apiKey: string;
}
