/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * These are the options for the assistant's voice.
 */
export type CreateAssistantDtoVoice =
    | Vapi.AzureVoice
    | Vapi.CartesiaVoice
    | Vapi.DeepgramVoice
    | Vapi.ElevenLabsVoice
    | Vapi.LmntVoice
    | Vapi.NeetsVoice
    | Vapi.OpenAiVoice
    | Vapi.PlayHtVoice
    | Vapi.RimeAiVoice;
