/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateMakeCredentialDto {
    provider: "make";
    /** Team ID */
    teamId: string;
    /** Region of your application. For example: eu1, eu2, us1, us2 */
    region: string;
    /** This is not returned in the API. */
    apiKey: string;
}
