/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateToolTemplateDtoVisibility = "public" | "private";

export const CreateToolTemplateDtoVisibility = {
    Public: "public",
    Private: "private",
} as const;
