/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * These are the options for the assistant's transcriber.
 */
export type CreateAssistantDtoTranscriber =
    | Vapi.DeepgramTranscriber
    | Vapi.GladiaTranscriber
    | Vapi.TalkscriberTranscriber;
