/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCustomerDto {
    /**
     * This is the flag to toggle the E164 check for the `number` field. This is an advanced property which should be used if you know your use case requires it.
     *
     * Use cases:
     *
     * - `false`: To allow non-E164 numbers like `+001234567890`, `1234`, or `abc`. This is useful for dialing out to non-E164 numbers on your SIP trunks.
     * - `true` (default): To allow only E164 numbers like `+14155551234`. This is standard for PSTN calls.
     *
     * If `false`, the `number` is still required to only contain alphanumeric characters (regex: `/^\+?[a-zA-Z0-9]+$/`).
     *
     * @default true (E164 check is enabled)
     */
    numberE164CheckEnabled?: boolean;
    /** This is the extension that will be dialed after the call is answered. */
    extension?: string;
    /** This is the number of the customer. */
    number?: string;
    /** This is the SIP URI of the customer. */
    sipUri?: string;
    /**
     * This is the name of the customer. This is just for your own reference.
     *
     * For SIP inbound calls, this is extracted from the `From` SIP header with format `"Display Name" <sip:username@domain>`.
     */
    name?: string;
}
