/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the tool that the block will call. To use an existing tool, use `toolId`.
 */
export type CreateToolCallBlockDtoTool =
    | Vapi.CreateDtmfToolDto
    | Vapi.CreateEndCallToolDto
    | Vapi.CreateVoicemailToolDto
    | Vapi.CreateFunctionToolDto
    | Vapi.CreateGhlToolDto
    | Vapi.CreateMakeToolDto
    | Vapi.CreateTransferCallToolDto;
