/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface CreateToolTemplateDto {
    details?: Vapi.CreateToolTemplateDtoDetails;
    providerDetails?: Vapi.CreateToolTemplateDtoProviderDetails;
    metadata?: Vapi.ToolTemplateMetadata;
    visibility?: Vapi.CreateToolTemplateDtoVisibility;
    type: "tool";
    /** The name of the template. This is just for your own reference. */
    name?: string;
    provider?: Vapi.CreateToolTemplateDtoProvider;
}
