/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateAnthropicCredentialDto {
    provider: "anthropic";
    /** This is not returned in the API. */
    apiKey: string;
}
