/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the tag for the token. It represents its scope.
 */
export type CreateTokenDtoTag = "private" | "public";

export const CreateTokenDtoTag = {
    Private: "private",
    Public: "public",
} as const;
