/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateGoHighLevelCredentialDto {
    provider: "gohighlevel";
    /** This is not returned in the API. */
    apiKey: string;
}
