/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeepgramVoiceIdEnum =
    | "asteria"
    | "luna"
    | "stella"
    | "athena"
    | "hera"
    | "orion"
    | "arcas"
    | "perseus"
    | "angus"
    | "orpheus"
    | "helios"
    | "zeus";

export const DeepgramVoiceIdEnum = {
    Asteria: "asteria",
    Luna: "luna",
    Stella: "stella",
    Athena: "athena",
    Hera: "hera",
    Orion: "orion",
    Arcas: "arcas",
    Perseus: "perseus",
    Angus: "angus",
    Orpheus: "orpheus",
    Helios: "helios",
    Zeus: "zeus",
} as const;
