/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeepgramTranscriberModel =
    | "nova-2"
    | "nova-2-general"
    | "nova-2-meeting"
    | "nova-2-phonecall"
    | "nova-2-finance"
    | "nova-2-conversationalai"
    | "nova-2-voicemail"
    | "nova-2-video"
    | "nova-2-medical"
    | "nova-2-drivethru"
    | "nova-2-automotive"
    | "nova"
    | "nova-general"
    | "nova-phonecall"
    | "nova-medical"
    | "enhanced"
    | "enhanced-general"
    | "enhanced-meeting"
    | "enhanced-phonecall"
    | "enhanced-finance"
    | "base"
    | "base-general"
    | "base-meeting"
    | "base-phonecall"
    | "base-finance"
    | "base-conversationalai"
    | "base-voicemail"
    | "base-video";

export const DeepgramTranscriberModel = {
    Nova2: "nova-2",
    Nova2General: "nova-2-general",
    Nova2Meeting: "nova-2-meeting",
    Nova2Phonecall: "nova-2-phonecall",
    Nova2Finance: "nova-2-finance",
    Nova2Conversationalai: "nova-2-conversationalai",
    Nova2Voicemail: "nova-2-voicemail",
    Nova2Video: "nova-2-video",
    Nova2Medical: "nova-2-medical",
    Nova2Drivethru: "nova-2-drivethru",
    Nova2Automotive: "nova-2-automotive",
    Nova: "nova",
    NovaGeneral: "nova-general",
    NovaPhonecall: "nova-phonecall",
    NovaMedical: "nova-medical",
    Enhanced: "enhanced",
    EnhancedGeneral: "enhanced-general",
    EnhancedMeeting: "enhanced-meeting",
    EnhancedPhonecall: "enhanced-phonecall",
    EnhancedFinance: "enhanced-finance",
    Base: "base",
    BaseGeneral: "base-general",
    BaseMeeting: "base-meeting",
    BasePhonecall: "base-phonecall",
    BaseFinance: "base-finance",
    BaseConversationalai: "base-conversationalai",
    BaseVoicemail: "base-voicemail",
    BaseVideo: "base-video",
} as const;
