/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ElevenLabsVoiceIdEnum =
    | "burt"
    | "marissa"
    | "andrea"
    | "sarah"
    | "phillip"
    | "steve"
    | "joseph"
    | "myra"
    | "paula"
    | "ryan"
    | "drew"
    | "paul"
    | "mrb"
    | "matilda"
    | "mark";

export const ElevenLabsVoiceIdEnum = {
    Burt: "burt",
    Marissa: "marissa",
    Andrea: "andrea",
    Sarah: "sarah",
    Phillip: "phillip",
    Steve: "steve",
    Joseph: "joseph",
    Myra: "myra",
    Paula: "paula",
    Ryan: "ryan",
    Drew: "drew",
    Paul: "paul",
    Mrb: "mrb",
    Matilda: "matilda",
    Mark: "mark",
} as const;
