/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the provider-specific ID that will be used. Ensure the Voice is present in your 11Labs Voice Library.
 */
export type ElevenLabsVoiceId = Vapi.ElevenLabsVoiceIdEnum | string;
