/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FileStatus = "indexed" | "not_indexed";

export const FileStatus = {
    Indexed: "indexed",
    NotIndexed: "not_indexed",
} as const;
