/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface File_ {
    object?: "file";
    status?: Vapi.FileStatus;
    /** This is the name of the file. This is just for your own reference. */
    name?: string;
    originalName?: string;
    bytes?: number;
    purpose?: string;
    mimetype?: string;
    key?: string;
    path?: string;
    bucket?: string;
    url?: string;
    metadata?: Record<string, unknown>;
    /** This is the unique identifier for the file. */
    id: string;
    /** This is the unique identifier for the org that this file belongs to. */
    orgId: string;
    /** This is the ISO 8601 date-time string of when the file was created. */
    createdAt: string;
    /** This is the ISO 8601 date-time string of when the file was last updated. */
    updatedAt: string;
}
