/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GcpKey {
    /** This is the type of the key. Most likely, this is "service_account". */
    type: string;
    /** This is the ID of the Google Cloud project associated with this key. */
    projectId: string;
    /** This is the unique identifier for the private key. */
    privateKeyId: string;
    /**
     * This is the private key in PEM format.
     *
     * Note: This is not returned in the API.
     */
    privateKey: string;
    /** This is the email address associated with the service account. */
    clientEmail: string;
    /** This is the unique identifier for the client. */
    clientId: string;
    /** This is the URI for the auth provider's authorization endpoint. */
    authUri: string;
    /** This is the URI for the auth provider's token endpoint. */
    tokenUri: string;
    /** This is the URL of the public x509 certificate for the auth provider. */
    authProviderX509CertUrl: string;
    /** This is the URL of the public x509 certificate for the client. */
    clientX509CertUrl: string;
    /** This is the domain associated with the universe this service account belongs to. */
    universeDomain: string;
}
