/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GladiaTranscriberLanguageBehaviour =
    | "manual"
    | "automatic single language"
    | "automatic multiple languages";

export const GladiaTranscriberLanguageBehaviour = {
    Manual: "manual",
    AutomaticSingleLanguage: "automatic single language",
    AutomaticMultipleLanguages: "automatic multiple languages",
} as const;
