/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GladiaTranscriberModel = "fast" | "accurate";

export const GladiaTranscriberModel = {
    Fast: "fast",
    Accurate: "accurate",
} as const;
