/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ImportTwilioPhoneNumberDto {
    /**
     * This is the fallback destination an inbound call will be transferred to if:
     *
     * 1. `assistantId` is not set
     * 2. `squadId` is not set
     * 3. and, `assistant-request` message to the `serverUrl` fails
     *
     * If this is not set and above conditions are met, the inbound call is hung up with an error message.
     */
    fallbackDestination?: Vapi.ImportTwilioPhoneNumberDtoFallbackDestination;
    /** These are the digits of the phone number you own on your Twilio. */
    twilioPhoneNumber: string;
    /** This is your Twilio Account SID that will be used to handle this phone number. */
    twilioAccountSid: string;
    /** This is the Twilio Auth Token that will be used to handle this phone number. */
    twilioAuthToken: string;
    /** This is the name of the phone number. This is just for your own reference. */
    name?: string;
    /**
     * This is the assistant that will be used for incoming calls to this phone number.
     *
     * If neither `assistantId` nor `squadId` is set, `assistant-request` will be sent to your Server URL. Check `ServerMessage` and `ServerMessageResponse` for the shape of the message and response that is expected.
     */
    assistantId?: string;
    /**
     * This is the squad that will be used for incoming calls to this phone number.
     *
     * If neither `assistantId` nor `squadId` is set, `assistant-request` will be sent to your Server URL. Check `ServerMessage` and `ServerMessageResponse` for the shape of the message and response that is expected.
     */
    squadId?: string;
    /**
     * This is the server URL where messages will be sent for calls on this number. This includes the `assistant-request` message.
     *
     * You can see the shape of the messages sent in `ServerMessage`.
     *
     * This overrides the `org.serverUrl`. Order of precedence: tool.server.url > assistant.serverUrl > phoneNumber.serverUrl > org.serverUrl.
     */
    serverUrl?: string;
    /**
     * This is the secret Vapi will send with every message to your server. It's sent as a header called x-vapi-secret.
     *
     * Same precedence logic as serverUrl.
     */
    serverUrlSecret?: string;
}
