/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InviteUserDtoRole = "admin" | "editor" | "viewer";

export const InviteUserDtoRole = {
    Admin: "admin",
    Editor: "editor",
    Viewer: "viewer",
} as const;
