/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the type of output you'd like.
 *
 * `string`, `number`, `integer`, `boolean` are the primitive types and should be obvious.
 *
 * `array` and `object` are more interesting and quite powerful. They allow you to define nested structures.
 *
 * For `array`, you can define the schema of the items in the array using the `items` property.
 *
 * For `object`, you can define the properties of the object using the `properties` property.
 */
export type JsonSchemaType = "string" | "number" | "integer" | "boolean" | "array" | "object";

export const JsonSchemaType = {
    String: "string",
    Number: "number",
    Integer: "integer",
    Boolean: "boolean",
    Array: "array",
    Object: "object",
} as const;
