/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LmntVoiceIdEnum = "lily" | "daniel";

export const LmntVoiceIdEnum = {
    Lily: "lily",
    Daniel: "daniel",
} as const;
