/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the specific resource, relevant only to API logs.
 */
export type LogResource = "assistant" | "phone-number" | "tool" | "squad" | "call" | "file" | "metric" | "log";

export const LogResource = {
    Assistant: "assistant",
    PhoneNumber: "phone-number",
    Tool: "tool",
    Squad: "squad",
    Call: "call",
    File: "file",
    Metric: "metric",
    Log: "log",
} as const;
