/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the request method.
 */
export type LogRequestHttpMethod = "POST" | "GET" | "PUT" | "PATCH" | "DELETE";

export const LogRequestHttpMethod = {
    Post: "POST",
    Get: "GET",
    Put: "PUT",
    Patch: "PATCH",
    Delete: "DELETE",
} as const;
