/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface LogsPaginatedResponse {
    results: Vapi.Log[];
    metadata: Vapi.PaginationMeta;
}
