/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the type of the log.
 */
export type LogType = "API" | "Webhook" | "Call" | "Provider";

export const LogType = {
    Api: "API",
    Webhook: "Webhook",
    Call: "Call",
    Provider: "Provider",
} as const;
