/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface MakeToolProviderDetails {
    /** This is the Template URL or the Snapshot URL corresponding to the Template. */
    templateUrl?: string;
    setupInstructions?: Vapi.ToolTemplateSetup[];
    /** The type of tool. "make" for Make tool. */
    type: "make";
    scenarioId?: number;
    scenarioName?: string;
    triggerHookId?: number;
    triggerHookName?: string;
}
