/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MessagePlan {
    /**
     * This are the messages that the assistant will speak when the user hasn't responded for `idleTimeoutSeconds`. Each time the timeout is triggered, a random message will be chosen from this array.
     *
     * Usage:
     *
     * - If user gets distracted and doesn't respond for a while, this can be used to grab their attention.
     * - If the transcriber doesn't pick up what the user said, this can be used to ask the user to repeat themselves. (From the perspective of the assistant, the conversation is idle since it didn't "hear" any user messages.)
     *
     * @default null (no idle message is spoken)
     */
    idleMessages?: string[];
    /**
     * This determines the maximum number of times `idleMessages` can be spoken during the call.
     *
     * @default 3
     */
    idleMessageMaxSpokenCount?: number;
    /**
     * This is the timeout in seconds before a message from `idleMessages` is spoken. The clock starts when the assistant finishes speaking and remains active until the user speaks.
     *
     * @default 10
     */
    idleTimeoutSeconds?: number;
}
