/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Monitor {
    /** This is the URL where the assistant's calls can be listened to in real-time. To enable, set `assistant.monitorPlan.listenEnabled` to `true`. */
    listenUrl?: string;
    /** This is the URL where the assistant's calls can be controlled in real-time. To enable, set `assistant.monitorPlan.controlEnabled` to `true`. */
    controlUrl?: string;
}
