/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OpenAiMessageRole = "assistant" | "function" | "user" | "system" | "tool";

export const OpenAiMessageRole = {
    Assistant: "assistant",
    Function: "function",
    User: "user",
    System: "system",
    Tool: "tool",
} as const;
