/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OpenAiModelFallbackModelsItem =
    | "gpt-4o-mini"
    | "gpt-4o-mini-2024-07-18"
    | "gpt-4o"
    | "gpt-4o-2024-05-13"
    | "gpt-4o-2024-08-06"
    | "gpt-4-turbo"
    | "gpt-4-turbo-2024-04-09"
    | "gpt-4-turbo-preview"
    | "gpt-4-0125-preview"
    | "gpt-4-1106-preview"
    | "gpt-4"
    | "gpt-4-0613"
    | "gpt-3.5-turbo"
    | "gpt-3.5-turbo-0125"
    | "gpt-3.5-turbo-1106"
    | "gpt-3.5-turbo-16k"
    | "gpt-3.5-turbo-0613";

export const OpenAiModelFallbackModelsItem = {
    Gpt4OMini: "gpt-4o-mini",
    Gpt4OMini20240718: "gpt-4o-mini-2024-07-18",
    Gpt4O: "gpt-4o",
    Gpt4O20240513: "gpt-4o-2024-05-13",
    Gpt4O20240806: "gpt-4o-2024-08-06",
    Gpt4Turbo: "gpt-4-turbo",
    Gpt4Turbo20240409: "gpt-4-turbo-2024-04-09",
    Gpt4TurboPreview: "gpt-4-turbo-preview",
    Gpt40125Preview: "gpt-4-0125-preview",
    Gpt41106Preview: "gpt-4-1106-preview",
    Gpt4: "gpt-4",
    Gpt40613: "gpt-4-0613",
    Gpt35Turbo: "gpt-3.5-turbo",
    Gpt35Turbo0125: "gpt-3.5-turbo-0125",
    Gpt35Turbo1106: "gpt-3.5-turbo-1106",
    Gpt35Turbo16K: "gpt-3.5-turbo-16k",
    Gpt35Turbo0613: "gpt-3.5-turbo-0613",
} as const;
