/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OrgPlan {
    includedProviders?: Record<string, unknown>[];
    includedMinutes?: number;
    costPerOverageMinute?: number;
}
