/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An emotion to be applied to the speech.
 */
export type PlayHtVoiceEmotion =
    | "female_happy"
    | "female_sad"
    | "female_angry"
    | "female_fearful"
    | "female_disgust"
    | "female_surprised"
    | "male_happy"
    | "male_sad"
    | "male_angry"
    | "male_fearful"
    | "male_disgust"
    | "male_surprised";

export const PlayHtVoiceEmotion = {
    FemaleHappy: "female_happy",
    FemaleSad: "female_sad",
    FemaleAngry: "female_angry",
    FemaleFearful: "female_fearful",
    FemaleDisgust: "female_disgust",
    FemaleSurprised: "female_surprised",
    MaleHappy: "male_happy",
    MaleSad: "male_sad",
    MaleAngry: "male_angry",
    MaleFearful: "male_fearful",
    MaleDisgust: "male_disgust",
    MaleSurprised: "male_surprised",
} as const;
