/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PlayHtVoiceIdEnum =
    | "jennifer"
    | "melissa"
    | "will"
    | "chris"
    | "matt"
    | "jack"
    | "ruby"
    | "davis"
    | "donna"
    | "michael";

export const PlayHtVoiceIdEnum = {
    Jennifer: "jennifer",
    Melissa: "melissa",
    Will: "will",
    Chris: "chris",
    Matt: "matt",
    Jack: "jack",
    Ruby: "ruby",
    Davis: "davis",
    Donna: "donna",
    Michael: "michael",
} as const;
