/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PunctuationBoundary =
    /**
     * 。 */
    | "\u3002"
    /**
     * ， */
    | "\uFF0C"
    /**
     * . */
    | "."
    /**
     * ! */
    | "!"
    /**
     * ? */
    | "?"
    /**
     * ; */
    | ";"
    /**
     * ) */
    | ")"
    /**
     * ، */
    | "\u060C"
    /**
     * ۔ */
    | "\u06D4"
    /**
     * । */
    | "\u0964"
    /**
     * ॥ */
    | "\u0965"
    /**
     * | */
    | "|"
    /**
     * || */
    | "||"
    /**
     * , */
    | ","
    /**
     * : */
    | ":";

export const PunctuationBoundary = {
    Circle: "\u3002",
    FullWidthComma: "\uFF0C",
    Dot: ".",
    Exclamation: "!",
    Question: "?",
    Semicolon: ";",
    Parenthesis: ")",
    ArabicComma: "\u060C",
    UrduFullStop: "\u06D4",
    BengaliFullStop: "\u0964",
    DoubleDanda: "\u0965",
    Pipe: "|",
    DoublePipe: "||",
    HalfWidthComma: ",",
    Colon: ":",
} as const;
