/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the type of the regex option. Options are:
 *
 * - `ignore-case`: Ignores the case of the text being matched.
 * - `whole-word`: Matches whole words only.
 * - `multi-line`: Matches across multiple lines.
 */
export type RegexOptionType = "ignore-case" | "whole-word" | "multi-line";

export const RegexOptionType = {
    IgnoreCase: "ignore-case",
    WholeWord: "whole-word",
    MultiLine: "multi-line",
} as const;
