/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the provider-specific ID that will be used.
 */
export type RimeAiVoiceId = Vapi.RimeAiVoiceIdEnum | string;
