/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used. Defaults to 'v1' when not specified.
 */
export type RimeAiVoiceModel = "v1" | "mist";

export const RimeAiVoiceModel = {
    V1: "v1",
    Mist: "mist",
} as const;
