/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the operator you want to use to compare the left side and right side.
 *
 * The operation becomes `(leftSide) operator (rightSide)`.
 */
export type RuleBasedConditionOperator = "eq" | "neq" | "gt" | "gte" | "lt" | "lte";

export const RuleBasedConditionOperator = {
    Eq: "eq",
    Neq: "neq",
    Gt: "gt",
    Gte: "gte",
    Lt: "lt",
    Lte: "lte",
} as const;
