/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the destination of the transfer.
 */
export type ServerMessageTransferUpdateDestination =
    | Vapi.TransferDestinationAssistant
    | Vapi.TransferDestinationStep
    | Vapi.TransferDestinationNumber
    | Vapi.TransferDestinationSip;
