/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the destination to forward the call to if the request is "forward".
 */
export type ServerMessagePhoneCallControlDestination = Vapi.TransferDestinationNumber | Vapi.TransferDestinationSip;
