/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the request to control the phone call.
 */
export type ServerMessagePhoneCallControlRequest = "forward" | "hang-up";

export const ServerMessagePhoneCallControlRequest = {
    Forward: "forward",
    HangUp: "hang-up",
} as const;
