/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export type ServerMessageEndOfCallReportCostsItem =
    | Vapi.TransportCost
    | Vapi.TranscriberCost
    | Vapi.ModelCost
    | Vapi.VoiceCost
    | Vapi.VapiCost
    | Vapi.AnalysisCost;
