/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

/**
 * This is the response that is expected from the server to the message.
 *
 * Note: Most messages don't expect a response. Only "assistant-request", "tool-calls" and "transfer-destination-request" do.
 */
export type ServerMessageResponseMessageResponse =
    | Vapi.ServerMessageResponseAssistantRequest
    | Vapi.ServerMessageResponseToolCalls
    | Vapi.ServerMessageResponseTransferDestinationRequest
    | Vapi.ServerMessageResponseVoiceRequest;
