/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ServerMessageResponseToolCalls {
    /** These are the results of the "tool-calls" message. */
    results?: Vapi.ToolCallResult[];
    /** This is the error message if the tool call was not successful. */
    error?: string;
}
