/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ServerMessageResponseTransferDestinationRequest {
    /** This is the destination you'd like the call to be transferred to. */
    destination?: Vapi.ServerMessageResponseTransferDestinationRequestDestination;
    /** This is the error message if the transfer should not be made. */
    error?: string;
}
