/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the role which the speech update is for.
 */
export type ServerMessageSpeechUpdateRole = "assistant" | "user";

export const ServerMessageSpeechUpdateRole = {
    Assistant: "assistant",
    User: "user",
} as const;
