/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the status of the speech update.
 */
export type ServerMessageSpeechUpdateStatus = "started" | "stopped";

export const ServerMessageSpeechUpdateStatus = {
    Started: "started",
    Stopped: "stopped",
} as const;
