/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ServerMessageResponse {
    /**
     * This is the response that is expected from the server to the message.
     *
     * Note: Most messages don't expect a response. Only "assistant-request", "tool-calls" and "transfer-destination-request" do.
     */
    messageResponse: Vapi.ServerMessageResponseMessageResponse;
}
