/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface StepDestination {
    type: "step";
    /** This is an optional array of conditions that must be met for this destination to be triggered. If empty, this is the default destination that the step transfers to. */
    conditions?: Vapi.StepDestinationConditionsItem[];
    stepName: string;
}
