/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface SyncVoiceLibraryDto {
    /** List of providers you want to sync. */
    providers?: Vapi.SyncVoiceLibraryDtoProvidersItem[];
}
