/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SyncVoiceLibraryDtoProvidersItem =
    | "11labs"
    | "azure"
    | "cartesia"
    | "custom-voice"
    | "deepgram"
    | "lmnt"
    | "neets"
    | "openai"
    | "playht"
    | "rime-ai";

export const SyncVoiceLibraryDtoProvidersItem = {
    ElevenLabs: "11labs",
    Azure: "azure",
    Cartesia: "cartesia",
    CustomVoice: "custom-voice",
    Deepgram: "deepgram",
    Lmnt: "lmnt",
    Neets: "neets",
    Openai: "openai",
    Playht: "playht",
    RimeAi: "rime-ai",
} as const;
