/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TemplateProvider = "make" | "gohighlevel" | "function";

export const TemplateProvider = {
    Make: "make",
    Gohighlevel: "gohighlevel",
    Function: "function",
} as const;
