/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TemplateVisibility = "public" | "private";

export const TemplateVisibility = {
    Public: "public",
    Private: "private",
} as const;
