/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the time step for aggregations.
 *
 * If not provided, defaults to returning for the entire time range.
 */
export type TimeRangeStep =
    | "minute"
    | "hour"
    | "day"
    | "week"
    | "month"
    | "quarter"
    | "year"
    | "decade"
    | "century"
    | "millennium";

export const TimeRangeStep = {
    Minute: "minute",
    Hour: "hour",
    Day: "day",
    Week: "week",
    Month: "month",
    Quarter: "quarter",
    Year: "year",
    Decade: "decade",
    Century: "century",
    Millennium: "millennium",
} as const;
