/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ToolMessageStart {
    /**
     * This message is triggered when the tool call starts.
     *
     * This message is never triggered for async tools.
     *
     * If this message is not provided, one of the default filler messages "Hold on a sec", "One moment", "Just a sec", "Give me a moment" or "This'll just take a sec" will be used.
     */
    type: "request-start";
    /** This is the content that the assistant says when this message is triggered. */
    content: string;
    /** This is an optional array of conditions that the tool call arguments must meet in order for this message to be triggered. */
    conditions?: Vapi.Condition[];
}
