/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToolTemplateSetup {
    title: string;
    description?: string;
    videoUrl?: string;
    docsUrl?: string;
}
