/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index";

export interface ToolCall {
    /** This is the type of tool the model called. */
    type: "function";
    /** This is the function the model called. */
    function: Vapi.ToolCallFunction;
    /** This is the unique identifier for the tool call. */
    id: string;
}
