/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToolTemplateMetadata {
    collectionType?: string;
    collectionId?: string;
    collectionName?: string;
}
