/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ToolCallFunction {
    /** This is the name of the function the model called. */
    name: string;
    /** These are the arguments that the function was called with. */
    arguments: Record<string, unknown>;
}
