/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransferMode = "rolling-history" | "swap-system-message-in-history";

export const TransferMode = {
    RollingHistory: "rolling-history",
    SwapSystemMessageInHistory: "swap-system-message-in-history",
} as const;
