/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdatePlayHtCredentialDto {
    provider: "playht";
    /** This is not returned in the API. */
    apiKey: string;
    userId: string;
}
