/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateToolTemplateDtoProvider = "make" | "gohighlevel" | "function";

export const UpdateToolTemplateDtoProvider = {
    Make: "make",
    Gohighlevel: "gohighlevel",
    Function: "function",
} as const;
