/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateRunpodCredentialDto {
    provider: "runpod";
    /** This is not returned in the API. */
    apiKey: string;
}
