/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateElevenLabsCredentialDto {
    provider: "11labs";
    /** This is not returned in the API. */
    apiKey: string;
}
