/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateTogetherAiCredentialDto {
    provider: "together-ai";
    /** This is not returned in the API. */
    apiKey: string;
}
