/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateRimeAiCredentialDto {
    provider: "rime-ai";
    /** This is not returned in the API. */
    apiKey: string;
}
