/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateTwilioCredentialDto {
    provider: "twilio";
    /** This is not returned in the API. */
    authToken: string;
    accountSid: string;
}
