/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateOpenAiCredentialDto {
    provider: "openai";
    /** This is not returned in the API. */
    apiKey: string;
}
