/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateGroqCredentialDto {
    provider: "groq";
    /** This is not returned in the API. */
    apiKey: string;
}
