/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateCustomLlmCredentialDto {
    provider: "custom-llm";
    /** This is not returned in the API. */
    apiKey: string;
}
