/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdatePerplexityAiCredentialDto {
    provider: "perplexity-ai";
    /** This is not returned in the API. */
    apiKey: string;
}
