/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateAnyscaleCredentialDto {
    provider: "anyscale";
    /** This is not returned in the API. */
    apiKey: string;
}
