/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateToolTemplateDtoVisibility = "public" | "private";

export const UpdateToolTemplateDtoVisibility = {
    Public: "public",
    Private: "private",
} as const;
