/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateVonageCredentialDto {
    provider: "vonage";
    /** This is not returned in the API. */
    apiSecret: string;
    apiKey: string;
}
