/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateOpenRouterCredentialDto {
    provider: "openrouter";
    /** This is not returned in the API. */
    apiKey: string;
}
