/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateCartesiaCredentialDto {
    provider: "cartesia";
    /** This is not returned in the API. */
    apiKey: string;
}
