/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateUserRoleDtoRole = "admin" | "editor" | "viewer";

export const UpdateUserRoleDtoRole = {
    Admin: "admin",
    Editor: "editor",
    Viewer: "viewer",
} as const;
