/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateDeepgramCredentialDto {
    provider: "deepgram";
    /** This is not returned in the API. */
    apiKey: string;
    /** This can be used to point to an onprem Deepgram instance. Defaults to api.deepgram.com. */
    apiUrl?: string;
}
