/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UpdateAzureOpenAiCredentialDtoRegion =
    | "australia"
    | "canada"
    | "eastus2"
    | "eastus"
    | "france"
    | "india"
    | "japan"
    | "northcentralus"
    | "norway"
    | "southcentralus"
    | "sweden"
    | "switzerland"
    | "uk"
    | "westus"
    | "westus3";

export const UpdateAzureOpenAiCredentialDtoRegion = {
    Australia: "australia",
    Canada: "canada",
    Eastus2: "eastus2",
    Eastus: "eastus",
    France: "france",
    India: "india",
    Japan: "japan",
    Northcentralus: "northcentralus",
    Norway: "norway",
    Southcentralus: "southcentralus",
    Sweden: "sweden",
    Switzerland: "switzerland",
    Uk: "uk",
    Westus: "westus",
    Westus3: "westus3",
} as const;
