/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VoiceLibraryVoiceResponse {
    voiceId: string;
    name: string;
    publicOwnerId?: string;
    description?: string;
    gender?: string;
    age?: Record<string, unknown>;
    accent?: string;
}
