/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The gender of the voice.
 */
export type VoiceLibraryGender = "male" | "female";

export const VoiceLibraryGender = {
    Male: "male",
    Female: "female",
} as const;
