/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type ToolsGetResponse =
    | Vapi.DtmfTool
    | Vapi.EndCallTool
    | Vapi.FunctionTool
    | Vapi.GhlTool
    | Vapi.MakeTool
    | Vapi.TransferCallTool
    | Vapi.OutputTool;
