/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type ToolsCreateRequest =
    | Vapi.CreateDtmfToolDto
    | Vapi.CreateEndCallToolDto
    | Vapi.CreateFunctionToolDto
    | Vapi.CreateGhlToolDto
    | Vapi.CreateMakeToolDto
    | Vapi.CreateTransferCallToolDto
    | Vapi.CreateOutputToolDto;
