/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VapiEnvironment = {
    Default: "https://api.vapi.ai",
} as const;

export type VapiEnvironment = typeof VapiEnvironment.Default;
