/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../../../index";

export type BlocksDeleteResponse = Vapi.ConversationBlock | Vapi.ToolCallBlock | Vapi.WorkflowBlock;
